# -*- coding: utf-8 -*-
"""Assignment1_CharviBajaj04701012025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tixP3R4z0uaket-_sa-tVz_d2jVLChBX
"""

# area of rectangle
length=int(input("enter the length:"))
breadth=int(input("enter the breadth:"))
area=length*breadth
print("area is :",area)

#simple interest
principle=int(input("enter principle :"))
rate=int(input ("enter rate:"))
time=int(input ("enter time:"))
Numerator=principle*rate*time
Simple_interest=Numerator/100
print("simple interest is:", Simple_interest)

#convert celsius to fahrenheit
celsius=int(input("enter the temperature in celsius:"))
fahrenheit=(celsius*1.8)+32
print("temperature after conversion is :",fahrenheit)

#average of 3 numbers
a=int(input("enter first number"))
b=int(input("enter second number"))
c=int(input("enter third number"))
average=(a+b+c)/3
print("average is:",average)

#square and cube of number
a=int(input("enter number :"))
square=a*a
cube=a*a*a
print("square is:",square)
print("cube is :",cube)

#swap two numbers
a=int(input("enter first number :"))
b=int(input("enter second number :"))
#swapping
a=a+b
b=a-b
a=a-b
print("after swap:")
print("first number becomes:",a)
print("second number becomes:",b)

# Student Report Program

# Taking student details
name = input("enter your name:")
roll_no = int(input("enter your roll number:"))

# Taking marks
maths = int(input("enter your marks for maths :"))
phy = int(input("enter your marks for physics :"))
webdev = int(input("enter your marks for web development :"))
english = int(input("enter your marks for english :"))

# Calculating total marks and percentage
total_marks = phy + maths + webdev + english
percentage = (total_marks * 100) / 400

# Displaying student report
print("STUDENT REPORT ")
print("Name:", name)
print("Roll Number:", roll_no)
print("Maths Marks:", maths)
print("Physics Marks:", phy)
print("Webdevelopment Marks:", webdev)
print("English Marks:", english)
print("Total Marks:", total_marks)
print("Percentage:", percentage, "%")