# -*- coding: utf-8 -*-
"""Week3_Assignment_CharviBajaj_04701012025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MuFvBZGfQTdzfeoK6TpQEJRjLKWE9Gfx
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix
df = pd.read_csv('agriculture_yield_dataset.csv')
df.head()

print("part A")
print("ques1")
#number of rows and columns
print("1.number of rows and columns",df.shape)
#name of the columns
print("2.names of all the columns",df.columns)
#display of the first 10 records
print("3.displaying the first 10 records")
df.head(10)

print("ques2")
#data type of each column
print(df.dtypes)
#identify where missing values are present
print(df.isnull().sum())
#mentioning the affected columns with missing values
missing_cols=df.columns[df.isnull().sum()]
print(missing_cols)

print("ques 3")

mean_values = df.mean(numeric_only=True)
# Feature with highest mean
highest_mean_feature = mean_values.idxmax()
highest_mean_value = mean_values.max()
print("Feature with highest mean:", highest_mean_feature)
print("Mean value:", highest_mean_value)

std_values = df.std(numeric_only=True)

# Feature with highest standard deviation
highest_std_feature = std_values.idxmax()
highest_std_value = std_values.max()

print("Feature with highest standard deviation:", highest_std_feature)
print("Standard deviation:", highest_std_value)

print("part B")
import matplotlib.pyplot as plt
import seaborn as sns
print("ques4")
#rainfall
plt.hist(df['rainfall_mm'], bins=20, edgecolor='black',color='green')
plt.title("Histogram of Rainfall (mm)")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Frequency")
plt.show()
#temperature
plt.hist(df['temperature_c'], bins=20, edgecolor='black', color='yellow')
plt.title("Histogram of Temperature (°C)")
plt.xlabel("Temperature (°C)")
plt.ylabel("Frequency")
plt.show()
# fertilizer
plt.hist(df['fertilizer_kg'], bins=20, edgecolor='black', color='blue')
plt.title("Histogram of Fertilizer (kg)")
plt.xlabel("Fertilizer (kg)")
plt.ylabel("Frequency")
plt.show()
#yield
plt.hist(df['yield_ton_per_hectare'], bins=20, edgecolor='black', color='purple')
plt.title("Histogram of Yield (tons/hectare)")
plt.xlabel("Yield (tons/hectare)")
plt.ylabel("Frequency")
plt.show()

"""observations about each histogram             
1.rainfall_mm: spreads between 300-1200                                         
               peaks are around 800-900                                      
2.temperature_c:peak value is obtained near mid 20s                            
                temperatures mostly range between 20-35 degree celsius       
3.fertilizer_kg:range is 50-200                                              
                no obvious peaks                                              
4.yield_ton_per_hectare: bell shaped                                         
                        most values around 5ton/hectare                                        
"""

print("ques5")
#crop type analysis
print("Crop Counts:", df['crop_type'].value_counts())
sns.countplot(x='crop_type', data=df)
plt.title("Crop Type Frequency")
plt.show()

"""cotton is the most frequent crop with 311 records"""

print("ques6")
print("Soil Counts:", df['soil_type'].value_counts())
sns.countplot(x='soil_type', data=df)
plt.title("Soil Type Frequency")
plt.show()

"""clay is most common soil type"""

print("ques7")
plt.hist(df['yield_ton_per_hectare'], bins=20, edgecolor='black',color='green')
plt.title("Yield Distribution")
plt.xlabel("Yield (tons/hectare)")
plt.ylabel("Frequency")
plt.show()

"""yes the distribution is apporximately normal                                 
no noticeable outliers
"""

print("ques8")
plt.scatter(df['rainfall_mm'], df['yield_ton_per_hectare'],color='green')
plt.title("Rainfall vs Yield")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (tons/hectare)")
plt.show()

plt.scatter(df['fertilizer_kg'], df['yield_ton_per_hectare'],color='orange')
plt.title("Fertilizer vs Yield")
plt.xlabel("Fertilizer (kg)")
plt.ylabel("Yield (tons/hectare)")
plt.show()

"""rainfall appears to have a stronger relationship with the yield"""

print("ques9")
corr = df.corr(numeric_only=True)
print("Correlation Matrix:", corr)
sns.heatmap(corr, annot=True, cmap="cool")
plt.title("Correlation Heatmap")
plt.show()

"""top three features correlated with the yield are:                            
1.fertilizer_kg                                                                 
2.rainfall_mm                                                             
3.irrigation_hours
"""

print("ques10")
print("Average Yield by Crop:", df.groupby('crop_type')['yield_ton_per_hectare'].mean())
print("Average Yield by Soil:", df.groupby('soil_type')['yield_ton_per_hectare'].mean())

"""rice crop type and loamy soil type have the highest average yield"""

print("part C")
print("ques11")
df_encoded = pd.get_dummies(df, columns=['crop_type','soil_type'])
print("First 5 Rows Encoded:", df_encoded.head())

print("ques12")
target= 'yield_ton_per_hectare'

X = df_encoded.drop(columns=[target])
y = df_encoded[target]
print("Target Variable:", target)

print("Input Features (X):")
print(X.head())

print("Target Variable (y):")
print(y.head())

"""yield_ton_per_hectare is being used as target column"""

print("part D")
print("ques13")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("ques14")
lr = LinearRegression()
lr.fit(X_train, y_train)
print("Model Coefficients:", lr.coef_)
print("Intercept:", lr.intercept_)

coef_df = pd.DataFrame({'Feature': X_train.columns, 'Coefficient': lr.coef_})
print("Feature with highest positive coefficient:", coef_df.loc[coef_df['Coefficient'].idxmax()])