# -*- coding: utf-8 -*-
"""Assignment2_CharviBajaj04701012025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rycJaRdvyTMCSbc0biLopW71eDkWjxhG
"""

#sum of first 10 natural numbers
sum=0
for i in range(1,11):
  sum+=i
print("sum of first 10 natural numbers is:",sum)

#factorial of a number
num = int(input("Enter a number: "))
fact = 1
for i in range(1, num+1):
    fact *= i
print("Factorial of", num, "is:", fact)

#fibonacci series
n = int(input("Enter number of terms: "))
a, b = 0, 1   # first two terms
print("Fibonacci Series:")
for i in range(n):
    print(a, end=" ")
    a, b = b, a + b

# largest among 3 numbers

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = int(input("Enter the third number: "))

if a > b and a > c:
    print("First number is largest")
elif b > a and b > c:
    print("Second number is largest")
else:
    print("Third number is largest")

# Student Result System
# Input student details
name = input("Enter student name: ")
roll_no = int(input("Enter roll number: "))
# Subjects
subjects = ["Maths", "Physics", "Web Development", "C Programming", "English"]
# Input marks using loop
total = 0
for subject in subjects:
    marks = int(input(f"Enter marks for {subject}: "))
    total += marks
percentage = total / 5
# Display grade using if-elif-else
if percentage >= 90:
    grade = "A"
elif percentage >= 75:
    grade = "B"
elif percentage >= 50:
    grade = "C"
else:
    grade = "D"
print("Name:", name)
print("Roll No.:", roll_no)
print("Total Marks:", total)
print("Percentage:", percentage)
print("Grade:", grade)